export const adminNavigation = [
  { href: "/admin", label: "Dashboard" },
  { href: "/admin/onboarding", label: "Onboarding" },
  { href: "/admin/leads", label: "Leads" },
  { href: "/admin/bookings", label: "Bookings" },
  { href: "/admin/contacts", label: "Contacts" },
  { href: "/admin/work-orders", label: "Work Orders" },
  { href: "/admin/clients", label: "Clients" },
  { href: "/admin/properties", label: "Properties" },
  { href: "/admin/estimates", label: "Estimates" },
  { href: "/admin/invoices", label: "Invoices" },
  { href: "/admin/payments", label: "Payments" },
  { href: "/admin/employees", label: "Employees" },
  { href: "/admin/availability", label: "Availability" },
  { href: "/admin/check-ins", label: "Check-Ins" },
  { href: "/admin/schedule", label: "Schedule" },
  { href: "/admin/communications", label: "Comms" },
  { href: "/admin/payroll", label: "Payroll" },
  { href: "/admin/integrations", label: "Integrations" },
  { href: "/admin/plans", label: "Plans" },
  { href: "/admin/reports", label: "Reports" },
  { href: "/admin/settings", label: "Settings" },
];
